// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function decode(json) {
  return Belt_Option.getExn(Js_json.decodeString(json));
}

export {
  decode ,
  
}
/* No side effect */
