// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Pervasives from "rescript/lib/es6/pervasives.js";

function toNumber(day) {
  return day + 1 | 0;
}

function fromNumber(number) {
  if (number > 7 || number < 1) {
    return Pervasives.failwith("No day of week");
  } else {
    return number - 1 | 0;
  }
}

function toRu(day) {
  switch (day) {
    case /* Monday */0 :
        return "Понедельник";
    case /* Tuesday */1 :
        return "Вторник";
    case /* Wednesday */2 :
        return "Среда";
    case /* Thursday */3 :
        return "Четверг";
    case /* Friday */4 :
        return "Пятница";
    case /* Saturday */5 :
        return "Суббота";
    case /* Sunday */6 :
        return "Воскресенье";
    
  }
}

function toEn(day) {
  switch (day) {
    case /* Monday */0 :
        return "Monday";
    case /* Tuesday */1 :
        return "Tuesday";
    case /* Wednesday */2 :
        return "Wednesday";
    case /* Thursday */3 :
        return "Thursday";
    case /* Friday */4 :
        return "Friday";
    case /* Saturday */5 :
        return "Saturday";
    case /* Sunday */6 :
        return "Sunday";
    
  }
}

var Day = {
  toNumber: toNumber,
  fromNumber: fromNumber,
  toRu: toRu,
  toEn: toEn
};

function fromNumber$1(n) {
  if (n !== 1) {
    if (n !== 2) {
      return Pervasives.failwith("");
    } else {
      return /* Even */1;
    }
  } else {
    return /* Uneven */0;
  }
}

function fromDate(date) {
  var day = date.getDate() | 0;
  var month = date.getMonth() | 0;
  var year = date.getFullYear() | 0;
  var month$1 = month + 1 | 0;
  var a = Js_math.floor((14 - month$1) / 12);
  var y = (year + 4800 | 0) - a | 0;
  var m = (month$1 + Math.imul(12, a) | 0) - 3 | 0;
  var j = (((((day + Js_math.floor((153 * m + 2) / 5) | 0) + Math.imul(365, y) | 0) + Js_math.floor(y / 4) | 0) - Js_math.floor(y / 100) | 0) + Js_math.floor(y / 400) | 0) - 32045 | 0;
  var d4 = ((j + 31741 | 0) - j % 7 | 0) % 146097 % 36524 % 1461;
  var l = Js_math.floor(d4 / 1460);
  var d1 = (d4 - l | 0) % 365 + l | 0;
  var week = Js_math.floor(d1 / 7) + 1 | 0;
  if (week % 2 === 0) {
    return /* Even */1;
  } else {
    return /* Uneven */0;
  }
}

var Week = {
  fromNumber: fromNumber$1,
  fromDate: fromDate
};

export {
  Day ,
  Week ,
  
}
/* No side effect */
